services:
  - type: web
    name: agricart
    runtime: php
    plan: free
    buildCommand: composer install
    startCommand: php -S 0.0.0.0:$PORT
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_TYPE
        value: pgsql
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASS
        sync: false
